encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.addpage, name="addpage"),
    path("edit", views.editpage, name="editpage"),
    path("random", views.randompage, name="randompage"),
    path("replace", views.replace, name="replace"),
    path("<str:pagename>", views.wikipage, name="wikipage")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.
class WikiEntry(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50)
    content = models.TextField()
    images = models.URLField()
    edits = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.title}"

encyclopedia/views.py
import random

from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist

from .models import *

import markdown2

from . import util

# Form for creating a new wiki page
class NewPageForm(forms.Form):
    pagename = forms.CharField(label="Page Title", initial="NewEntryTitle", required=True)
    content = forms.CharField(widget=forms.Textarea(), label="Content", initial="Information about your new entry.", required=True)
    images = forms.CharField(label="Image URLs (separate with new lines)", initial="https://imgur.com/a/thisisanexample")

def index(request):
    entries = WikiEntry.objects.all()

    if request.method == "POST":
        query = request.POST.get("q")
        matches = []
        queryLower = query.lower()

        for entry in entries:
            if queryLower == entry.title.lower():
                return redirect('wiki:wikipage', pagename = entry.title)
            elif queryLower in entry.title.lower():
                matches.append(entry.title)

        if len(matches) > 0:
            return render(request, "encyclopedia/index.html", {
                "entries": matches,
                "title": "Matching Pages:"
            })
        else:
            return render(request, "encyclopedia/index.html", {
                "entries": None,
                "title": "No Matching Pages Found :("
            })
    else:
        edits = 0
        for entry in entries:
            edits = edits + entry.edits

        return render(request, "encyclopedia/index.html", {
            "entries": WikiEntry.objects.values_list("title", flat=True).order_by("title"),
            "title": "All Pages:",
            "numberOfEntries": len(entries),
            "numberOfEdits": edits
        })

def addpage(request):
    if request.method == "POST":
        form = NewPageForm(request.POST)
        newTitle = form.data["pagename"]
        newContent = form.data["content"]
        newImages = form.data["images"]

        # Check to see if a page with that title already exists
        existingTitles = WikiEntry.objects.values_list("title", flat=True).order_by("title")
        titleLower = newTitle.lower()
        for existingTitle in existingTitles:
            if titleLower == existingTitle.lower():
                # TODO: Add an error message here
                return render(request, "encyclopedia/addpage.html", {
                            "form": form
                })
        
        # Page with that title does not currently exist, safe to create new file
        e = WikiEntry(
            title=newTitle,
            content=newContent,
            images=newImages
        )
        e.save()

        # Successfully created page, load the newly-created page
        return HttpResponseRedirect(reverse("wiki:wikipage", args=(newTitle,)))
    else:
        return render(request, "encyclopedia/addpage.html", {
            "form": NewPageForm()
        })
    
def editpage(request):
    if request.method == "GET":
        pagename = request.GET.get("entry")
        previouspage = WikiEntry.objects.get(title=pagename)

        return render(request, "encyclopedia/editpage.html", {
            "entry": pagename,
            "editable": previouspage.content,
            "editable_image_links": previouspage.images
        })
    else:
        form = NewPageForm(request.POST)

        if form.is_valid:
            newPagename = request.POST.get("entry")
            newContent = request.POST.get("content")
            newImages = request.POST.get("images")

            pageToBeEdited = WikiEntry.objects.get(title=newPagename)

            pageToBeEdited.title = newPagename
            pageToBeEdited.content = newContent
            pageToBeEdited.images  = newImages
            pageToBeEdited.edits = pageToBeEdited.edits + 1

            pageToBeEdited.save()

            return HttpResponseRedirect(f"/{newPagename}")
        else:
            return render(request, "encyclopedia/editpage.html", {
                "entry": form.data["pagename"],
                "editable": form,
                "editable_image_links": newImages
        })

def wikipage(request, pagename):
    try:
        entry = WikiEntry.objects.get(title=pagename)

        # Parse image URLs
        images = []
        for url in entry.images.splitlines():
            images.append(url)

        return render(request, "encyclopedia/wikipage.html", {
            "pagename": pagename,
            "entry": markdown2.markdown(entry.content),
            "gallery": images
        })
    except ObjectDoesNotExist:
        return render(request, "encyclopedia/wikipage.html", {
            "pagename": pagename,
            "entry": "Error: Requested page was not found"
        })

def randompage(request):
    pages = WikiEntry.objects.all()
    if len(pages) > 0:
        luckynum = random.randint(0, len(pages) - 1)

        return redirect('wiki:wikipage', pagename = pages[luckynum].title)
    else:
        return render(request, "encyclopedia/index.html", {
            "entries": None,
            "title": "There are no pages :("
        })
    
def replace(request):
    if request.method == "POST":
        form = NewPageForm(request.POST)
        oldWord = form.data["toBeReplaced"]
        newWord = form.data["toReplaceWith"]

        # Validate the form

        # No spaces (single word only)
        if ( " " in oldWord) or ( " " in newWord ):
            return render(request, "encyclopedia/replace.html", {
                "error": "Words cannot include spaces (single words only, please!)"
            })
        
        # Minimum length
        if (len(oldWord) < 3) or (len(newWord) < 3):
            return render(request, "encyclopedia/replace.html", {
                "error": "Word must be at least 3 characters in length.)"
            })
        
        # Search pages and make changes
        entries = WikiEntry.objects.all()
        for entry in entries:
            newContent = entry.content.replace(oldWord, newWord)
            entry.content = newContent
            entry.save()

        # Successfully made changes, return to home page
        return redirect('wiki:index')
    else:
        return render(request, "encyclopedia/replace.html", {
            "error": ""
        })

encyclopedia/templates/encyclopedia/addpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create a New Page
{% endblock %}

{% block body %}

<form action="{% url 'wiki:addpage' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/editpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Editing {{ entry }}
{% endblock %}

{% block body %}

<h1>Editing {{ entry }}</h1>

<form action="{% url 'wiki:editpage' %}" method="post">
    {% csrf_token %}
    <textarea name="content" cols="20" rows="6" required="" id="id_content">{{ editable }}</textarea>
    <textarea name="images" cols="20" rows="3" required="" id="id_images">{{ editable_image_links }}</textarea>
    <input type="hidden" name="entry" value="{{entry}}">
    <input type="submit" value="Submit">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Welcome to WikiPlus!</h1> <br/>

    <h3>Pages Created: {{ numberOfEntries }}</h3>
    <h3>Edits Made: {{ numberOfEdits }}</h3><br/>

    <h2>{{ title }}</h2>

    <ul>
        {% for entry in entries %}
        <li><a href="{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
    
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.3.js"></script>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Gaegu">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        <link rel="icon" type="image/png" href="{% static 'encyclopedia/favicon.ico' %}"/>
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>WikiPlus</h2>
                <form action="{% url 'wiki:index' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:addpage' %}">Create a New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:randompage' %}">Random Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:replace' %}">Find & Replace</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

<script src="{% static 'encyclopedia/tabs.js' %}"></script>

encyclopedia/templates/encyclopedia/replace.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Replace
{% endblock %}

{% block body %}

<h1>Replace</h1>
<h2>{{ error }}</h2>
<h3>Replaces each instance of a word with that of another word. This will search and edit across ALL pages.</h3>
<form action="{% url 'wiki:replace' %}" method="post" onsubmit="return confirm('Are you sure you want to submit?');">
    {% csrf_token %}
    <label for="old">Old word:</label><br>
    <input type="text" id="old" name="toBeReplaced" minlength=3 required><br>
    <label for="new">New word:</label><br>
    <input type="text" id="new" name="toReplaceWith" minlength=3 required><br><br>
    <input type="submit" value="Submit">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/wikipage.html
{% extends "encyclopedia/layout.html" %}

{% load static %}

{% block title %}
    {{ pagename }}
{% endblock %}

{% block body %}

<div id="page-header">
    <div id="page-title">{{ pagename }}</div>
    <ul id="tabs">
        <li><button id="content-tab">Main Article</button></li>
        <li><button id="gallery-tab">Mood Board</button></li>
    </ul>
</div>

<div id="content-view">
    {{ entry|safe }}
</div>

<div id="gallery-view" style="display: none;">
    {% for image in gallery %}
    <img id="gallery-image" src="{{ image }}"></a>
    {% endfor %}
</div>

<form action="{% url 'wiki:editpage' %}" method="get">
    <input type="hidden" name="entry" value="{{pagename}}">
    <input type="submit" value="Edit">
</form>

{% endblock %}

<script src="{% static 'encyclopedia/tabs.js' %}"></script>